### PR TITLE
correct grammar issues, and rewrite for clarity. 

### PR DESCRIPTION
**Pull request by miker**
(Only up to the ZFS section)

### CODE REVIEW

**Comment by miker** [comment]
All excellent catches. I'll make the changes and push if they haven't been
done already.

Thanks!

Mike

**Comment by miker** [comment]
All of the above issues should now be resolved. Apologies for the line lengths, I let a few of them get away from me. Should be good now. I did leave the url for the FreeBSD handbook security section on the same line. I wasn't 100% sure if a line break here would break the link.

**Comment by miker** [comment]
I was going back and forth between "of the" and "in the" for the "Security Section in the FreeBSD Handbook" link. As you can see, decided on "in the".

**Comment by Mrt134** [comment]
Sorry about being unresponsive - I've been completely engrossed in another project. Your changes look great! Thanks again for contributing!

**Comment by miker** [comment]
No problem, i know how it goes when you're busy. Glad the changes looked good. Will hopefully have some time to do more soon.

**Pull request merged**
