### PR TITLE
s?/autofs?/.autofs?g

### PR DESCRIPTION
**Pull request by cryptorick**
Maybe the paths used to be under `/autofs`, but now (i.e., under `trueos-stable-17.12`) I see them under `/.autofs`.

### CODE REVIEW

**Comment by q5sys** [comment]
@pkgdemon I'm seeing the same under unstable.  Was this change intentional or accidental?  I dont want to change the docs for an unintentional change that we're going to undo.

**Comment by Mrt134** [comment]
I'll check on this before I merge. Either way, thanks for the fix!

**Comment by beanpole135** [comment]
The change from "/autofs"  to "/.autofs" for the default mountpoint was intentional. This helps prevent that special directory structure from being automatically scanned/browsed/locked by users and/or automated filesystem monitors.

**Comment by cryptorick** [comment]
@Mrt134 np. But I owe you and the team a ton more thanks for TrueOS. Thanks, guys!

**Pull request merged**
